[package]
authors = [
    "Dilshod Tadjibaev (@antimora)",
    "Nathaniel Simard (@nathanielsimard)",
]
description = "ONNX-IR is a pure Rust library for parsing ONNX models into an intermediate representation that can be used to generate code for various ML/DL frameworks"
edition = "2024"
license = "MIT OR Apache-2.0"
name = "onnx-ir"
readme = "README.md"
repository = "https://github.com/tracel-ai/burn/tree/main/crates/onnx-ir"
documentation = "https://docs.rs/onnx-ir"
version = "0.20.1"

[workspace]

[features]
default = ["mmap"]
mmap = ["memmap2"]

[dependencies]
burn-tensor = { version = "0.20.1", default-features = false }
onnx-ir-derive = { version = "0.20.1" }
bytemuck = { version = "1.24.0", features = ["extern_crate_alloc"] }
derive-new = { version = "0.7.0", default-features = false }
half = { version = "2.7.1", features = ["bytemuck"], default-features = false }
log = { version = "0.4.29", default-features = false }
protobuf = { version = "3.7.2", features = ["with-bytes"] }
regex = { version = "1.12.1", default-features = false, features = ["default"] }
serde = { version = "1.0.228", default-features = false, features = ["derive", "alloc"] }
strum = { version = "0.27.2", features = ["derive"] }
bytes = { version = "1.10", default-features = false }
memmap2 = { version = "0.9", optional = true }

[build-dependencies]
protobuf-codegen = "3.7.2"

[dev-dependencies]
pretty_assertions = "1.4.1"
rstest = "0.26.1"
tempfile = "3.24.0"
divan = "0.1"

[[bench]]
name = "mmap_loading"
harness = false
